title: Article Time
languageCode: de-DE

enableGitInfo: true
lastmod: ["lastmod", ":git", "date"] 

taxonomies:
  category: categories
  tag: tags
  author: authors
  series: series

markup:
  goldmark:
    renderer:
      unsafe : true