title: Article Time
languageCode: de-DE
languageName: Deutsch

enableGitInfo: true
lastmod: ["lastmod", ":git", "date"] 

taxonomies:
  category: categories
  tag: tags
  author: authors
  series: series

markup:
  goldmark:
    renderer:
      unsafe : true

permalinks:
  articles: "/:section/:year/:month/:slug/"
  year: "/articles/:slug/"
  month: "/articles/:slug/"


imaging:
  quality: 75
  bgColor: "#ffffff"
  exif:
    disableDate: true
    disableLatLong: true