remixicon_version: 1750019714996
reading_speed: 179
default_author: "angel"
author:
  name: "Angel"
  # email: "mail@article-time.de"
follow:
  header:
    - name: "RSS Feed"
      src: "/index.xml"
      icon: "rss-line"
  footer:
    - name: "RSS Feed"
      src: "/index.xml"
      icon: "rss-line"
    