title = "Private Blog"
baseURL = "/"
languageCode = "de-DE"
theme = "article"

# TODO: Robots Metatag testen
enableRobotsTXT = true
enableGitInfo = true

DefaultContentLanguage = "de"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""

[sitemap]
  changefreq = "weekly"
  priority = "0.9"
  filename = "sitemap.xml"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[frontmatter]
  lastmod = [":git", "lastmod"]

[taxonomies]
  year = "year"
  month = "month"
  tags = "tags"
  category = "categories"
  series = "series"

[permalinks]
  articles = "/:section/:year/:month/:slug/"
  year = "/articles/:slug/"
  month = "/articles/:slug/"

[related]
  threshold = 0 
  includeNewer = true
  toLower = false
  [[related.indices]]
    name = "categories"
    weight = 100
  [[related.indices]]
    name = "date"
    weight = 10

[params]
  author = "Angel Crawford"
  favicon = "favicon.ico"
  description = "The last theme you'll ever need. Maybe. dsds"

  [params.seo]
    # TODO: Keywords bestimmen
    # TODO: Author, wenn Autoren bestimmt werden, dass hier weg nehmen, an die SEO Sachen im Header denken
    twitterHandle = "crawford_ftw" #Twitter name, to bind shared cards to your profile
    keywords = "Webcard, Profil Karte, Angel Crawford"

  # TODO: Soziale Medien einfügen
  [params.social]
    facebook = "#"
    twitter = "#"
    instagram = "#"
    github = "#"
    rss = "/index.xml"
  
  [params.post_settings]
    recent_posts_number = 2
    show_reading_time = true
