title: Article Time
baseURL: https://angelcrawford.github.io/blog/

build:
  buildStats:
    enable: true
module:
  hugoVersion:
    extended: true
    min: "0.115.0"
  mounts:
    - source: "assets"
      target: "assets"
    - source: "hugo_stats.json"
      target: "assets/watching/hugo_stats.json"
