csp:
  default: ["'self'"]
  formaction: ["'self'"]
  framesrc: ["'self'"]
  imgsrc: ["'self'", "https://github.com", "https://*.githubusercontent.com", "https://icons.duckduckgo.com"]
  objectsrc: ["'none'"]
  stylesrc: ["'self'", "'unsafe-inline'", "'unsafe-eval'", "https://unpkg.com"]
  scriptsrc: ["'self'", "'unsafe-inline'", "'unsafe-eval'", "https://unpkg.com", "https://api.bloggify.net"]
  scriptsrcelem: ["'self'", "'unsafe-inline'", "'unsafe-eval'", "https://unpkg.com", "https://api.bloggify.net"]
  connectsrc: ["'self'", "https://api.bloggify.net"]