# This is a basic workflow to help you get started with Actions

name: hugo publish

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      # with:
      #   submodules: true

    - name: Build
      run: hugo --minify
